package org.stormdev.authlib.json.response;

/**
 * All possible errors for serverAuths
 *
 */
public enum ServerAuthError {
	/**
	 * The user isn't logged in/their session is invalid
	 */
	INVALIDSESSION, 
	/**
	 * The user hasn't requested dual authentication, or it has been over a minute since they did
	 */
	NOCLIENTREQUEST, 
	/**
	 * The AuthKey doesn't match the one generated by StormDev.org
	 */
	BADAUTHKEY;
}
